import React, { useState, useEffect, useRef, useMemo } from "react";
import markdownRenderer from "@/lib/markdown/MarkdownRenderer";
import SkateErrorBoundary from "./SkateErrorBoundary";
import { Skeleton } from "@chakra-ui/react";
import { observeHeicImages } from "@/lib/utils/heicImageFallback";
import { observeBrokenImages } from "@/lib/utils/brokenImageFallback";
import dynamic from "next/dynamic";

const ThreeSpeakPlayer = dynamic(
  () => import("@/components/markdown/ThreeSpeakPlayer").then((m) => m.ThreeSpeakPlayer),
  { ssr: false }
);
const VideoEmbed = dynamic(
  () => import("@/components/markdown/VideoEmbed").then((m) => m.VideoEmbed),
  { ssr: false }
);

interface HiveMarkdownProps {
  markdown: string;
  className?: string;
  style?: React.CSSProperties;
  disableVideoAutoplay?: boolean;
  /** Keep iframes as-is without converting to video tags (simpler preview) */
  rawIframes?: boolean;
}

const HiveMarkdown: React.FC<HiveMarkdownProps> = ({
  markdown,
  className = "markdown-body",
  style,
  disableVideoAutoplay = false,
  rawIframes = false,
}) => {
  const [renderedHtml, setRenderedHtml] = useState<string>("");
  const [isLoading, setIsLoading] = useState(true);
  const lastProcessedRef = useRef<{ markdown: string; disableAutoplay: boolean; html: string } | null>(null);
  const containerRef = useRef<HTMLDivElement>(null);

  // Observe the container for HEIC images and convert them on the fly
  useEffect(() => {
    if (!containerRef.current || isLoading) return;
    return observeHeicImages(containerRef.current);
  }, [renderedHtml, isLoading]);

  // Swap broken content images (dead IPFS CIDs, etc.) to a placeholder so a
  // single bad image doesn't spam the console with 4xx errors or show the
  // browser's broken-image glyph. Capture phase: `error` events don't bubble.
  useEffect(() => {
    if (!containerRef.current || isLoading) return;
    return observeBrokenImages(containerRef.current);
  }, [renderedHtml, isLoading]);

  useEffect(() => {
    // Skip full processing for rawIframes mode - handled by useMemo below
    if (rawIframes) {
      setIsLoading(false);
      return;
    }

    // Check if we've already processed this exact combination
    if (
      lastProcessedRef.current &&
      lastProcessedRef.current.markdown === markdown &&
      lastProcessedRef.current.disableAutoplay === disableVideoAutoplay
    ) {
      // Already processed, skip
      return;
    }

    let mounted = true;

    const processMarkdown = async () => {
      try {
        setIsLoading(true);

        // Full processing via markdownRenderer
        const rawHtml = await markdownRenderer(markdown);

        if (!mounted) return;

        // Convert YouTube placeholders AND any YouTube iframes (generated by
        // @hiveio/content-renderer's YoutubeEmbedder for markdown-style YT links)
        // back to a single [[YOUTUBE:id]] token so the render pass below can
        // mount the YouTubeLite component (high-res poster + click-to-play).
        const processYouTubeEmbeds = (html: string) => {
          let out = html.replace(
            /<div class=["']videoWrapper["'][^>]*>\s*<iframe[^>]*src=["'](?:https?:)?\/\/(?:www\.)?(?:youtube(?:-nocookie)?\.com\/embed\/|youtu\.be\/)([a-zA-Z0-9_-]{11})[^"']*["'][^>]*><\/iframe>\s*<\/div>/gi,
            (_m, videoId) => `[[YOUTUBE:${videoId}]]`
          );
          out = out.replace(
            /<iframe[^>]*src=["'](?:https?:)?\/\/(?:www\.)?(?:youtube(?:-nocookie)?\.com\/embed\/|youtu\.be\/)([a-zA-Z0-9_-]{11})[^"']*["'][^>]*><\/iframe>/gi,
            (_m, videoId) => `[[YOUTUBE:${videoId}]]`
          );
          return out;
        };

        // Remove autoplay from videos if disabled
        const processVideoAutoplay = (html: string) => {
          if (!disableVideoAutoplay) return html;

          return html.replace(/<video([^>]*?)>/gi, (match) => {
            return match.replace(/\s+autoplay/gi, "").replace(/\s+muted/gi, "");
          });
        };

        // Process YouTube embeds then handle autoplay
        let processedHtml = processYouTubeEmbeds(rawHtml);
        processedHtml = processVideoAutoplay(processedHtml);

        // Store in cache AFTER processing is complete
        lastProcessedRef.current = {
          markdown,
          disableAutoplay: disableVideoAutoplay,
          html: processedHtml,
        };

        setRenderedHtml(processedHtml);
      } catch (error) {
        console.error("Error processing markdown:", error);
        setRenderedHtml("<pre>" + markdown + "</pre>");
      } finally {
        if (mounted) {
          setIsLoading(false);
        }
      }
    };

    processMarkdown();

    return () => {
      mounted = false;
    };
  }, [markdown, disableVideoAutoplay, rawIframes]);

  // For rawIframes mode: render with stable iframe elements
  // Text content updates don't cause iframe reloads because iframes have stable keys
  const rawIframesContent = useMemo(() => {
    if (!rawIframes) return null;

    const parts: React.ReactNode[] = [];
    const iframeRegex = /<iframe[^>]*src=["']([^"']+)["'][^>]*>[\s\S]*?<\/iframe>/gi;
    let match;
    let lastIndex = 0;
    let partIndex = 0;

    while ((match = iframeRegex.exec(markdown)) !== null) {
      // Add text before this iframe
      if (match.index > lastIndex) {
        const textBefore = markdown.slice(lastIndex, match.index);
        const processedText = textBefore
          .replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<img src="$2" alt="$1" style="max-width:100%; border-radius:8px;" />')
          .replace(/\n/g, "<br />");
        const textKey = "text-" + partIndex;
        partIndex++;
        parts.push(
          <span key={textKey} dangerouslySetInnerHTML={{ __html: processedText }} />
        );
      }

      // Add iframe with stable key based on src
      const src = match[1];
      const iframeKey = "iframe-" + src;
      parts.push(
        <iframe
          key={iframeKey}
          src={src}
          style={{ maxWidth: "100%", borderRadius: "8px", aspectRatio: "16/9", width: "100%", height: "400px" }}
          frameBorder="0"
          allowFullScreen
        />
      );

      lastIndex = match.index + match[0].length;
    }

    // Add remaining text after last iframe
    if (lastIndex < markdown.length) {
      const textAfter = markdown.slice(lastIndex);
      const processedText = textAfter
        .replace(/!\[([^\]]*)\]\(([^)]+)\)/g, '<img src="$2" alt="$1" style="max-width:100%; border-radius:8px;" />')
        .replace(/\n/g, "<br />");
      const textKey = "text-" + partIndex;
      parts.push(
        <span key={textKey} dangerouslySetInnerHTML={{ __html: processedText }} />
      );
    }

    return parts;
  }, [markdown, rawIframes]);

  if (isLoading && !rawIframes) {
    return (
      <SkateErrorBoundary>
        <div className={className} style={style}>
          <Skeleton height="20px" mb={2} />
          <Skeleton height="20px" mb={2} />
          <Skeleton height="15px" width="70%" />
        </div>
      </SkateErrorBoundary>
    );
  }

  // For rawIframes mode: use React elements to keep iframes stable
  if (rawIframes) {
    return (
      <SkateErrorBoundary>
        <div ref={containerRef} className={className} style={style}>
          {rawIframesContent}
        </div>
      </SkateErrorBoundary>
    );
  }

  const htmlParts = renderedHtml.split(
    /(\[\[(?:3SPEAK|YOUTUBE):[^\]]+\]\])/g
  );
  const hasEmbed = htmlParts.length > 1;

  if (!hasEmbed) {
    return (
      <SkateErrorBoundary>
        <div
          ref={containerRef}
          className={className}
          style={style}
          dangerouslySetInnerHTML={{ __html: renderedHtml }}
        />
      </SkateErrorBoundary>
    );
  }

  return (
    <SkateErrorBoundary>
      <div ref={containerRef} className={className} style={style}>
        {htmlParts.map((part, i) => {
          const ts = part.match(/^\[\[3SPEAK:([^\]]+)\]\]$/);
          if (ts) {
            return <ThreeSpeakPlayer key={`3speak-${i}`} videoId={ts[1]} />;
          }
          const yt = part.match(/^\[\[YOUTUBE:([^\]]+)\]\]$/);
          if (yt) {
            return (
              <VideoEmbed key={`youtube-${i}`} type="YOUTUBE" id={yt[1]} index={i} />
            );
          }
          if (!part) return null;
          return (
            <span key={i} dangerouslySetInnerHTML={{ __html: part }} />
          );
        })}
      </div>
    </SkateErrorBoundary>
  );
};

export default React.memo(HiveMarkdown);
